dist: trusty

addons:
  sonarcloud:
    organization: "defra"

language: ruby
rvm: 2.4.2
cache: bundler

# Travis CI uses shallow clone to speed up build times, but a truncated SCM
# history may cause issues when SonarCloud computes blame data. To avoid this,
# you can access the full SCM history with `depth: false`
git:
  depth: false

env:
  global:
    - COMPANIES_HOUSE_API_KEY=secretkey

before_install:
  - export TZ=UTC
  - gem install -v 1.17.3 bundler --no-rdoc --no-ri

script:
  - bundle exec rubocop --format progress --format json --out rubocop-result.json
  - bundle exec rspec
  - sonar-scanner

deploy:
  provider: rubygems
  api_key:
    secure: kkd5povFz9W9RG/L3Z/XSMn6wvYrKEXDEyxAIKvFAeexrybJJdunIwU0xgc402xk3iHUlf8YI98bUsBekLxUDC5JFKC0t8Ad9JZP64wX6RoHItP5XJq8s2+1YWRC0/lsts6oEA6MguSwVH4c/SltMcSkvNJeDMj2IQYdZJuiOPDh9OHqQav5lyfpRc7DynwZ3HHAI4sR8Jp/zkMGLH04d0zCqqN317nW2IYuMtQGuXLbE0zyf7jvwwl0vx1YOey4SHcXMheGGmhbsZFn5Fb5a43YtwoMy09WpITScbjsB74FBVKAS9EKrXkcJSp+YoREUuULq2f2OXS+rkqHbHJqvL7D4Y0XpWlr7Hj79bxP7C01Q+bz0/PtGASdhC6IeL6yQmQwnRhocferWANY+74iVAnf7mLwX/mqbJvX9NX4r9B5jJEwY735BpC6Nmk+S+Bi5zBL1yunVhIZrGwB4NlJTu8Y38Wu68WeaK7Q9AKtHwFWmxNlENqbl67jpfdmLtCSvAcxKrydtPggMlkD9NCgax/yonSyMAVDoK/naobilqVTblBkgmXBSKxCmD/CB4QmszquevCIToVcaeVwVvEBzK1dogS4cDZHjPnvtg++cxuNSAEW55FaT3Z41DC/LWzXiJyKxPylCNa48orkIvIH0SBDNveheqPVChNeqxg3omI=
  gem: defra_ruby_validators
  on:
    tags: true
    repo: DEFRA/defra-ruby-validators
